<!DOCTYPE html>
<html>
<head><title>OX_WRAPPER "STRIXSPIDER" log log output(30/December/2017)</title></head>
<body>
<table>
<thead><tr>
<th colspan="2">OX_WRAPPER "STRIXSPIDER" log log output(30/December/2017)</th>
</tr></thead>
<tbody>
<tr bgcolor="#f2f2f2">
<td align="center">/30/December/2017/ (20:22:59.817133)</td><td align="right">*****************Log started*****************</td>
</tr><tr bgcolor="#ff0000">
<td align="center">/30/December/2017/ (20:22:60.000000)</td><td align="right"><b>ox_wrapper has thrown exception at line 21 in function "ox_wrapper::OxProgram::OxProgram" located at source file "d:\repos\rt_framework\ox_wrapper\ox_wrapper\program.cpp"</b></td>
</tr><tr bgcolor="#f2f2f2">
<td align="center">/30/December/2017/ (20:22:60.000000)</td><td align="right">*****************End of the log*****************


</td>
</tr></tbody>
</table>
</body>
</html
